// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParksAPI.Models;

namespace NationalParksAPI.Migrations
{
    [DbContext(typeof(NationalParksAPIContext))]
    partial class NationalParksAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NationalParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.HasIndex("StateId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "Crater Lake inspires awe. Native Americans witnessed its formation 7,700 years ago, when a violent eruption triggered the collapse of a tall peak. Scientists marvel at its purity: fed by rain and snow, it’s the deepest lake in the USA and one of the most pristine on earth. Artists, photographers, and sightseers gaze in wonder at its blue water and stunning setting atop the Cascade Mountain Range. https://www.nps.gov/crla/index.htm",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Crater_Lake_winter_pano2.jpg/1920px-Crater_Lake_winter_pano2.jpg",
                            Latitude = -122.10899999999999,
                            Longitude = 42.944600000000001,
                            Name = "Crater Lake",
                            StateId = 37
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "Colorful rock formations at John Day Fossil Beds preserve a world class record of plant and animal evolution, changing climate, and past ecosystems that span over 40 million years.  Exhibits and a working lab at the Thomas Condon Paleontology and Visitor Center as well as scenic drives and hikes at all three units allow visitors to explore the prehistoric past of Oregon and see science in action. https://www.nps.gov/joda/index.htm",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Sheep_Rock_near_sunset.jpg/1920px-Sheep_Rock_near_sunset.jpg",
                            Latitude = -119.63200000000001,
                            Longitude = 44.544600000000003,
                            Name = "John Day Fossil Beds",
                            StateId = 37
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Deep within the Siskiyou Mountains are dark, twisting passages that await your discovery.  Eons of acidic water seeping into marble rock created and decorated the wondrous “Marble Halls of Oregon.” Join a tour, get a taste of what caving is all about, and explore a mountain from the inside and out! https://www.nps.gov/orca/index.htm",
                            ImageUrl = "https://www.nationalparks.org/sites/default/files/Oregon%20Caves_NPS.jpg",
                            Latitude = -123.40441714603401,
                            Longitude = 42.095557533208179,
                            Name = "Marble Halls of Oregon",
                            StateId = 37
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "At the end of the last Ice Age, about 18,000 to 15,000 years ago, an ice dam in northern Idaho created Glacial Lake Missoula in Montana. The ice dam burst and released flood waters across Washington and down the Columbia River back flooding into Oregon before eventually reaching the Pacific Ocean. Happening perhaps a 100 times. Forever changing the lives and landscape of the Pacific Northwest. https://www.nps.gov/iafl/index.htm",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/6/69/Dry_Falls_%28Washington%29.jpg",
                            Latitude = -119.347401676649,
                            Longitude = 47.604616902324103,
                            Name = "Dry Falls",
                            StateId = 47
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "The ancient geologic landscape of the upper Columbia River cradles Lake Roosevelt in walls of stone carved by massive ice age floods. Come explore the shorelines and learn the stories of American Indians, traders and trappers, settlers and dam builders who called this place home. Swim, boat, hike, camp, and fish at this hidden gem in Northeast Washington, created by the Grand Coulee Dam. https://www.nps.gov/laro/index.htm",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Gifford_Ferry.JPG/1280px-Gifford_Ferry.JPG",
                            Latitude = -118.2466,
                            Longitude = 48.101100000000002,
                            Name = "Lake Roosevelt",
                            StateId = 47
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "The Pearl Harbor attack intensified existing hostility towards Japanese Americans. As wartime hysteria mounted, President Roosevelt signed Executive Order 9066 forcing over 120,000 West Coast persons of Japanese ancestry (Nikkei) to leave their homes, jobs, and lives behind, forcing them into one of ten prison camps spread across the nation because of their ethnicity. This is Minidoka's story. https://www.nps.gov/miin/index.htm",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Minidoka_National_Historic_Site_%28Entrance%29.jpg/1920px-Minidoka_National_Historic_Site_%28Entrance%29.jpg",
                            Latitude = -114.243914786209,
                            Longitude = 42.679045350072919,
                            Name = "Minidoka National Historic Site",
                            StateId = 12
                        },
                        new
                        {
                            ParkId = 7,
                            Description = "Ascending to 14,410 feet above sea level, Mount Rainier stands as an icon in the Washington landscape. An active volcano, Mount Rainier is the most glaciated peak in the contiguous U.S.A., spawning five major rivers. Subalpine wildflower meadows ring the icy volcano while ancient forest cloaks Mount Rainier’s lower slopes. Wildlife abounds in the park’s ecosystems. A lifetime of discovery awaits. https://www.nps.gov/mora/index.htm",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG/1280px-Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG",
                            Latitude = -121.7269,
                            Longitude = 46.880000000000003,
                            Name = "Mount Rainier",
                            StateId = 47
                        });
                });

            modelBuilder.Entity("NationalParksAPI.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "Alabama"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Alaska"
                        },
                        new
                        {
                            StateId = 3,
                            StateName = "Arizona"
                        },
                        new
                        {
                            StateId = 4,
                            StateName = "Arkansas"
                        },
                        new
                        {
                            StateId = 5,
                            StateName = "California"
                        },
                        new
                        {
                            StateId = 6,
                            StateName = "Colorado"
                        },
                        new
                        {
                            StateId = 7,
                            StateName = "Connecticut"
                        },
                        new
                        {
                            StateId = 8,
                            StateName = "Delaware"
                        },
                        new
                        {
                            StateId = 9,
                            StateName = "Florida"
                        },
                        new
                        {
                            StateId = 10,
                            StateName = "Georgia"
                        },
                        new
                        {
                            StateId = 11,
                            StateName = "Hawaii"
                        },
                        new
                        {
                            StateId = 12,
                            StateName = "Idaho"
                        },
                        new
                        {
                            StateId = 13,
                            StateName = "Illinois"
                        },
                        new
                        {
                            StateId = 14,
                            StateName = "Indiana"
                        },
                        new
                        {
                            StateId = 15,
                            StateName = "Iowa"
                        },
                        new
                        {
                            StateId = 16,
                            StateName = "Kansas"
                        },
                        new
                        {
                            StateId = 17,
                            StateName = "Kentucky"
                        },
                        new
                        {
                            StateId = 18,
                            StateName = "Louisiana"
                        },
                        new
                        {
                            StateId = 19,
                            StateName = "Maine"
                        },
                        new
                        {
                            StateId = 20,
                            StateName = "Maryland"
                        },
                        new
                        {
                            StateId = 21,
                            StateName = "Massachusetts"
                        },
                        new
                        {
                            StateId = 22,
                            StateName = "Michigan"
                        },
                        new
                        {
                            StateId = 23,
                            StateName = "Minnesota"
                        },
                        new
                        {
                            StateId = 24,
                            StateName = "Mississippi"
                        },
                        new
                        {
                            StateId = 25,
                            StateName = "Missouri"
                        },
                        new
                        {
                            StateId = 26,
                            StateName = "Montana"
                        },
                        new
                        {
                            StateId = 27,
                            StateName = "Nebraska"
                        },
                        new
                        {
                            StateId = 28,
                            StateName = "Nevada"
                        },
                        new
                        {
                            StateId = 29,
                            StateName = "New Hampshire"
                        },
                        new
                        {
                            StateId = 30,
                            StateName = "New Jersey"
                        },
                        new
                        {
                            StateId = 31,
                            StateName = "New Mexico"
                        },
                        new
                        {
                            StateId = 32,
                            StateName = "New York"
                        },
                        new
                        {
                            StateId = 33,
                            StateName = "North Carolina"
                        },
                        new
                        {
                            StateId = 34,
                            StateName = "North Dakota"
                        },
                        new
                        {
                            StateId = 35,
                            StateName = "Ohio"
                        },
                        new
                        {
                            StateId = 36,
                            StateName = "Oklahoma"
                        },
                        new
                        {
                            StateId = 37,
                            StateName = "Oregon"
                        },
                        new
                        {
                            StateId = 38,
                            StateName = "Pennsylvania"
                        },
                        new
                        {
                            StateId = 39,
                            StateName = "Rhode Island"
                        },
                        new
                        {
                            StateId = 40,
                            StateName = "South Carolina"
                        },
                        new
                        {
                            StateId = 41,
                            StateName = "South Dakota"
                        },
                        new
                        {
                            StateId = 42,
                            StateName = "Tennessee"
                        },
                        new
                        {
                            StateId = 43,
                            StateName = "Texas"
                        },
                        new
                        {
                            StateId = 44,
                            StateName = "Utah"
                        },
                        new
                        {
                            StateId = 45,
                            StateName = "Vermont"
                        },
                        new
                        {
                            StateId = 46,
                            StateName = "Virginia"
                        },
                        new
                        {
                            StateId = 47,
                            StateName = "Washington"
                        },
                        new
                        {
                            StateId = 48,
                            StateName = "West Virginia"
                        },
                        new
                        {
                            StateId = 49,
                            StateName = "Wisconsin"
                        },
                        new
                        {
                            StateId = 50,
                            StateName = "Wyoming"
                        });
                });

            modelBuilder.Entity("NationalParksAPI.Models.Park", b =>
                {
                    b.HasOne("NationalParksAPI.Models.State", null)
                        .WithMany("Parks")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NationalParksAPI.Models.State", b =>
                {
                    b.Navigation("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
